"""Generate or check the committed TrackJSON schema."""

from __future__ import annotations

import argparse
from importlib.resources import files
from pathlib import Path

from pystormtracker.schemas.generate import encode_trackjson_schema

_REGENERATION_COMMAND = "uv run python scripts/generate_trackjson_schema.py"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="compare generated bytes with the committed schema without writing",
    )
    parser.add_argument(
        "--write",
        action="store_true",
        help="write the generated schema to the source tree",
    )
    args = parser.parse_args()
    if args.check and args.write:
        parser.error("--check and --write are mutually exclusive")

    expected = encode_trackjson_schema()
    packaged_schema = files("pystormtracker.schemas").joinpath("trackjson.schema.json")
    if args.check:
        actual = packaged_schema.read_bytes()
        if actual != expected:
            print(
                f"TrackJSON schema is stale; regenerate it with {_REGENERATION_COMMAND}"
            )
            return 1
        print("TrackJSON schema is up to date")
        return 0

    if args.write or not args.check:
        path = (
            Path(__file__).parents[1]
            / "src/pystormtracker/schemas/trackjson.schema.json"
        )
        path.write_bytes(expected)
        print(f"Wrote {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
